# Configuration for the fact check system

# The main address pattern sent out as the From address on fact check emails
# If we ever want to change this format, we'll need to support some notion of
# legacy formats, so we still pick up emails to old addresses
address_format: <%=ENV.fetch("FACT_CHECK_ADDRESS_FORMAT", "factcheck+dev-{id}@alphagov.co.uk") %>
subject_format: <%=ENV.fetch("FACT_CHECK_SUBJECT_FORMAT", "\\[.+?\\] GOV.UK preview of new edition \\[dev-(?<id>.+?)\\]") %>

fetcher:
  address: <%=ENV.fetch("FACT_CHECK_ADDRESS", "imap.gmail.com") %>
  port: <%=ENV.fetch("FACT_CHECK_PORT", 993) %>
  user_name: <%=ENV["FACT_CHECK_USERNAME"] %>
  password: <%=ENV["FACT_CHECK_PASSWORD"] %>
  enable_ssl: true
