# Configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
---
:verbose: true
:concurrency: 2
<% if ENV.key?('SIDEKIQ_LOGFILE') %>
:logfile: <%= ENV['SIDEKIQ_LOGFILE'] %>
<% end %>
:queues:
  - default
